image now uses bullseye slim

diff --git a/.github/workflows/prod-pr-wf.yml b/.github/workflows/prod-pr-wf.yml
--- a/.github/workflows/prod-pr-wf.yml
+++ b/.github/workflows/prod-pr-wf.yml
@@ -4,7 +4,26 @@ on:
     branches:
       - "prod"
 jobs:
-  version-check:
+  version-check-repo:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Get version
+        run: BASEDIR=$(pwd) ./tools/get_version.sh
+      - name: Set version
+        run: BASEDIR=$(pwd) ./tools/get_version.sh >> $GITHUB_ENV
+      - name: Check if tag exist
+        run: |
+          TAG=$(git tag -l ${{ env.VERSION }})
+          if [ -n "$TAG" ]
+          then
+            echo "::error::This modulector version tag ($TAG) already exists in repository."
+            exit 1
+          fi       
+  version-check-docker:
     runs-on: ubuntu-latest
 
     steps:
